name: flutter-cloud-run

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: us-east1
  # project-name but it can be anything you want
  REPO_NAME: ci-cd

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

#      - name: Build and tag the docker image
#        run: |-
#            docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Github Checkout
        uses: actions/checkout@v4

      - name: Docker Build with cache
        uses: whoan/docker-build-with-cache-action@next
        with:
          username: _json_key
          password: "${{ secrets.GCLOUD_JSON_KEY }}"
          registry: gcr.io
          image_name: $REPO_NAME
          image_tag: $GITHUB_SHA


      - name: Push the image to the Google Container Registry (GCR)
        run: |-
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
          --platform "managed" \
          --allow-unauthenticated \
          --quiet

